version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: projecthub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-projecthub}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projecthub_password}
      POSTGRES_DB: ${POSTGRES_DB:-projecthub_mcp}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - projecthub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-projecthub} -d ${POSTGRES_DB:-projecthub_mcp}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend (Alpine.js - Lightweight and working)
  frontend:
    build:
      context: ./new-frontend
      dockerfile: Dockerfile
    container_name: projecthub-frontend
    restart: unless-stopped
    ports:
      - "8090:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - projecthub-network
    environment:
      - API_URL=/api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  projecthub-network:
    driver: bridge