services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: projecthub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: projecthub
      POSTGRES_PASSWORD: projecthub123
      POSTGRES_DB: projecthub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - projecthub-network

  # Frontend (Alpine.js - Lightweight and working)
  frontend:
    build:
      context: ./new-frontend
      dockerfile: Dockerfile
    container_name: projecthub-frontend
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - projecthub-network
    environment:
      - API_URL=/api

volumes:
  postgres_data:
    driver: local

networks:
  projecthub-network:
    driver: bridge