version: '3.8'

services:
  backend:
    image: anubissbe/projecthub-mcp-backend:latest
    container_name: projecthub-mcp-backend
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ORIGIN=${FRONTEND_URL:-http://localhost:5173}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    restart: unless-stopped

  frontend:
    image: anubissbe/projecthub-mcp-frontend:latest
    container_name: projecthub-mcp-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:3001/api}
      - VITE_WS_URL=${WS_URL:-ws://localhost:3001}
    restart: unless-stopped