version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: projecthub-mcp-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://mcp_user:mcp_secure_password_2024@172.19.0.4:5432/mcp_learning
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - projecthub-mcp-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: projecthub-mcp-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - VITE_WS_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - projecthub-mcp-network

networks:
  projecthub-mcp-network:
    external: true
    name: projecthub-mcp_network