name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-dependabot:
    runs-on: [self-hosted, docker, runnerhub]
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Auto-merge Dependabot PRs
      uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        command: merge
        approve-only: false
        merge-method: squash
        
  label-pr:
    runs-on: [self-hosted, docker, runnerhub]
    permissions:
      contents: read
      pull-requests: write
      
    steps:
    - name: Label PR based on paths
      uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true