name: ЁЯЪА CI/CD Pipeline (Disabled)

# This workflow is disabled and replaced by main.yml
# Created temporarily to clear stale docker-security configuration

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  disabled:
    name: тЪая╕П Workflow Disabled
    runs-on: ubuntu-latest
    steps:
      - name: тЪая╕П Workflow Disabled Notice
        run: |
          echo "This workflow has been disabled and replaced by main.yml"
          echo "All security scanning is now handled in the main workflow"
          exit 0