name: 🚀 CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Frontend Tests
  frontend-test:
    name: 🎨 Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🔍 Run ESLint
      run: npm run lint
      
    - name: 🧪 Run tests
      run: npm run test:coverage
      
    - name: 📊 Upload coverage reports
      uses: codecov/codecov-action@v5
      with:
        files: ./frontend/coverage/lcov.info
        flags: frontend
        name: frontend-coverage
        
    - name: 🏗️ Build frontend
      run: npm run build
      
    - name: 📤 Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/dist/

  # Backend Tests
  backend-test:
    name: 🔧 Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
        
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🧪 Run tests
      run: npm test -- --coverage
      env:
        DATABASE_URL: postgresql://test_user:test_pass@localhost:5432/test_db
        NODE_ENV: test
        
    - name: 📊 Upload coverage reports
      uses: codecov/codecov-action@v5
      with:
        files: ./backend/coverage/lcov.info
        flags: backend
        name: backend-coverage
        
    - name: 🏗️ Build backend
      run: npm run build

  # Docker Build and Security
  docker-security:
    name: 🐳 Docker & Security
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test]
    
    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v4
      
    - name: 🐳 Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: 🏗️ Build frontend image
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        tags: task-management-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: 🏗️ Build backend image
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: false
        tags: task-management-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: 🔍 Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: 📤 Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # E2E Tests
  e2e-tests:
    name: 🧪 E2E Tests
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test]
    
    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 🐳 Start services
      run: |
        docker compose -f docker-compose.ci.yml up -d --wait
        sleep 30
        
    - name: 🧪 Install E2E test dependencies
      working-directory: ./tests
      run: npm ci
      
    - name: 🧪 Run E2E tests
      working-directory: ./tests
      run: npm test
      
    - name: 📸 Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: e2e-screenshots
        path: tests/screenshots/
        
    - name: 🛑 Stop services
      if: always()
      run: docker compose -f docker-compose.ci.yml down

  # Code Quality
  code-quality:
    name: 📊 Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    # SonarCloud scan temporarily disabled to fix CI issues
    # - name: 🔍 SonarCloud Scan
    #   uses: SonarSource/sonarcloud-github-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: ⚠️ SonarCloud Skipped
      run: echo "SonarCloud scan temporarily disabled - can be re-enabled with SONAR_TOKEN"
        
    - name: 📊 CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: javascript,typescript
        
    - name: 📊 Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

  # Performance Tests
  # Temporarily disabled - TODO: Re-enable once all other CI issues are resolved
  # performance:
  #   name: ⚡ Performance Tests
  #   runs-on: ubuntu-latest
  #   needs: [docker-security]

  # Deployment (only on main branch)
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test, docker-security, e2e-tests]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v4
      
    - name: 🚀 Deploy to production
      run: |
        echo "🚀 Deploying to production..."
        echo "This would trigger your deployment process"
        # Add your deployment commands here
        
    - name: 📱 Notify deployment
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        text: "Deployment ${{ job.status }} for Task Management WebUI"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}