version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    groups:
      react:
        patterns:
          - "react*"
          - "@tanstack/*"
      dev-tools:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "vite*"
          - "vitest*"
      testing:
        patterns:
          - "@testing-library/*"
          - "playwright*"

  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    groups:
      express:
        patterns:
          - "express*"
          - "cors"
          - "helmet"
      database:
        patterns:
          - "pg*"
          - "redis*"
      dev-tools:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript*"
      testing:
        patterns:
          - "jest*"
          - "supertest*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3

  # Docker
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
    
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"