name: Manual Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Manual trigger test
        run: |
          echo "This workflow was triggered manually"
          echo "Date: $(date)"
          echo "Runner: $(uname -a)"