name: Simple CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Basic test
        run: |
          echo "Testing basic functionality"
          ls -la
          
      - name: Check backend files
        run: |
          echo "Checking backend directory"
          ls -la backend-fix/ || echo "Backend directory not found"